//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Prefabs/Mitya/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Prefabs.Mitya.Scripts
{
    public partial class @InputControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""TankActionMap"",
            ""id"": ""04f284ad-023a-4aca-944e-da67ded31bf4"",
            ""actions"": [
                {
                    ""name"": ""BodyMove"",
                    ""type"": ""Value"",
                    ""id"": ""717f4f04-de16-4b3c-bdb9-e24c1549aa05"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BodySpeedFactor"",
                    ""type"": ""Value"",
                    ""id"": ""d1498258-bec6-4c29-8c16-9d23b19882e0"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BodyRotationMode"",
                    ""type"": ""Button"",
                    ""id"": ""7b13dbae-0212-463a-b7c4-5943b7b87581"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HeadRotate"",
                    ""type"": ""Value"",
                    ""id"": ""bbaf720e-cb19-4210-9991-9aeb2dca5989"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HeadReset"",
                    ""type"": ""Button"",
                    ""id"": ""088255f0-095e-4e06-bc52-583f3e97da5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""09f815f2-9710-40fe-aed1-2039318adc6b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""BodyMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33bb6176-0672-4f1f-ae22-9308087bc6a9"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": """",
                    ""action"": ""BodySpeedFactor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3cc4a68-1b47-4d77-9a05-715d5430e34e"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BodyRotationMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dd677f0-3746-42c0-8cc6-8b67ff13cc58"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""HeadRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""556fc164-483c-4f22-8265-8fa5ef942f7c"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeadReset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // TankActionMap
            m_TankActionMap = asset.FindActionMap("TankActionMap", throwIfNotFound: true);
            m_TankActionMap_BodyMove = m_TankActionMap.FindAction("BodyMove", throwIfNotFound: true);
            m_TankActionMap_BodySpeedFactor = m_TankActionMap.FindAction("BodySpeedFactor", throwIfNotFound: true);
            m_TankActionMap_BodyRotationMode = m_TankActionMap.FindAction("BodyRotationMode", throwIfNotFound: true);
            m_TankActionMap_HeadRotate = m_TankActionMap.FindAction("HeadRotate", throwIfNotFound: true);
            m_TankActionMap_HeadReset = m_TankActionMap.FindAction("HeadReset", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // TankActionMap
        private readonly InputActionMap m_TankActionMap;
        private List<ITankActionMapActions> m_TankActionMapActionsCallbackInterfaces = new List<ITankActionMapActions>();
        private readonly InputAction m_TankActionMap_BodyMove;
        private readonly InputAction m_TankActionMap_BodySpeedFactor;
        private readonly InputAction m_TankActionMap_BodyRotationMode;
        private readonly InputAction m_TankActionMap_HeadRotate;
        private readonly InputAction m_TankActionMap_HeadReset;
        public struct TankActionMapActions
        {
            private @InputControls m_Wrapper;
            public TankActionMapActions(@InputControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @BodyMove => m_Wrapper.m_TankActionMap_BodyMove;
            public InputAction @BodySpeedFactor => m_Wrapper.m_TankActionMap_BodySpeedFactor;
            public InputAction @BodyRotationMode => m_Wrapper.m_TankActionMap_BodyRotationMode;
            public InputAction @HeadRotate => m_Wrapper.m_TankActionMap_HeadRotate;
            public InputAction @HeadReset => m_Wrapper.m_TankActionMap_HeadReset;
            public InputActionMap Get() { return m_Wrapper.m_TankActionMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(TankActionMapActions set) { return set.Get(); }
            public void AddCallbacks(ITankActionMapActions instance)
            {
                if (instance == null || m_Wrapper.m_TankActionMapActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_TankActionMapActionsCallbackInterfaces.Add(instance);
                @BodyMove.started += instance.OnBodyMove;
                @BodyMove.performed += instance.OnBodyMove;
                @BodyMove.canceled += instance.OnBodyMove;
                @BodySpeedFactor.started += instance.OnBodySpeedFactor;
                @BodySpeedFactor.performed += instance.OnBodySpeedFactor;
                @BodySpeedFactor.canceled += instance.OnBodySpeedFactor;
                @BodyRotationMode.started += instance.OnBodyRotationMode;
                @BodyRotationMode.performed += instance.OnBodyRotationMode;
                @BodyRotationMode.canceled += instance.OnBodyRotationMode;
                @HeadRotate.started += instance.OnHeadRotate;
                @HeadRotate.performed += instance.OnHeadRotate;
                @HeadRotate.canceled += instance.OnHeadRotate;
                @HeadReset.started += instance.OnHeadReset;
                @HeadReset.performed += instance.OnHeadReset;
                @HeadReset.canceled += instance.OnHeadReset;
            }

            private void UnregisterCallbacks(ITankActionMapActions instance)
            {
                @BodyMove.started -= instance.OnBodyMove;
                @BodyMove.performed -= instance.OnBodyMove;
                @BodyMove.canceled -= instance.OnBodyMove;
                @BodySpeedFactor.started -= instance.OnBodySpeedFactor;
                @BodySpeedFactor.performed -= instance.OnBodySpeedFactor;
                @BodySpeedFactor.canceled -= instance.OnBodySpeedFactor;
                @BodyRotationMode.started -= instance.OnBodyRotationMode;
                @BodyRotationMode.performed -= instance.OnBodyRotationMode;
                @BodyRotationMode.canceled -= instance.OnBodyRotationMode;
                @HeadRotate.started -= instance.OnHeadRotate;
                @HeadRotate.performed -= instance.OnHeadRotate;
                @HeadRotate.canceled -= instance.OnHeadRotate;
                @HeadReset.started -= instance.OnHeadReset;
                @HeadReset.performed -= instance.OnHeadReset;
                @HeadReset.canceled -= instance.OnHeadReset;
            }

            public void RemoveCallbacks(ITankActionMapActions instance)
            {
                if (m_Wrapper.m_TankActionMapActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ITankActionMapActions instance)
            {
                foreach (var item in m_Wrapper.m_TankActionMapActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_TankActionMapActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public TankActionMapActions @TankActionMap => new TankActionMapActions(this);
        public interface ITankActionMapActions
        {
            void OnBodyMove(InputAction.CallbackContext context);
            void OnBodySpeedFactor(InputAction.CallbackContext context);
            void OnBodyRotationMode(InputAction.CallbackContext context);
            void OnHeadRotate(InputAction.CallbackContext context);
            void OnHeadReset(InputAction.CallbackContext context);
        }
    }
}
